# Default presets
# You can add a custom path

&STARSHIP == ~/.config/starship.toml
&FISH == ~/.config/fish/config.fish
&BASH == ~/.bashrc
&ZSH == ~/.zshrc

# The below line determines the path. Default is ~/.bashrc.
$SHELL == ~/.bashrc